# Generated by Django 4.1.4 on 2024-07-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_superuser_status', 'Can view superuser status')]},
        ),
    ]
